name: Update Photo Gallery

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper git diff

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update gallery
        id: update
        run: |
          # Run the update script
          npm run update-gallery
          # Store the exit code
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Create Pull Request if changes
        if: steps.update.outputs.exit_code == 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 Update photo gallery"
          title: "🤖 Update photo gallery"
          body: |
            This PR updates the photo gallery with the latest changes.
            
            Changes made:
            - Updated images.json with latest photos
            - Converted any unsupported formats to JPG
            - Updated gallery metadata
            
            This is an automated update from the gallery update workflow.
          branch: update-gallery
          base: main
          delete-branch: true
          labels: |
            automated pr
            gallery update
